### ISSUE TITLE
Research + Implement: Redundant AD01/AD02 Setup

### ISSUE THREAD

**Issue by ItsMmmike** [SomethingGeneric/sparkle.local#4]
## To-Do:
Will work on implementing AD01 as our DC and configure AD02 as a redundant backup for AD DS and DNS services for our Final Project network environment. Additionally, MGMT01 will be joined to the new domain and configured with RSAT tools to enable easier management of the new AD Server Core VMs.

## Tasks:

- [x] Basic networking and setup of the AD01, AD02, and MGMT01 VMs
- [x] Promote AD01 to DC + Add AD02 and MGMT01 to the new domain
- [x] Configure AD02 as a Redundant DC via MGMT01
- [x] Update Team w/ Documentation (+ Config info if needed)
- [x] Also Update Team with AD Domain Admin Accounts
- [x] Win?
